# Supabase Configuration for Connectouch Blockchain AI Platform

project_id = "connectouch-blockchain-ai"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://connectouch-blockchain-ai.netlify.app"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false

[auth.external.github]
enabled = false

[auth.external.google]
enabled = false

[db]
major_version = 15

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
api_url = "http://localhost:54321"

[inbucket]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = true

[analytics]
enabled = false

[functions.crypto-prices]
verify_jwt = false

[functions.defi-protocols]
verify_jwt = false

[functions.ai-analysis]
verify_jwt = true

[functions.portfolio-sync]
verify_jwt = true

[functions.health-check]
verify_jwt = false

[functions.market-overview]
verify_jwt = false

[functions.real-time-updates]
verify_jwt = false

[functions.nft-collections]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false
