[build]
  publish = "apps/frontend/dist"
  command = "cd apps/frontend && npm install --legacy-peer-deps && npm run build:full"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://aompecyfgnakkmldhidg.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvbXBlY3lmZ25ha2ttbGRoaWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzMwODYsImV4cCI6MjA2OTMwOTA4Nn0.SSbGerxCplUZd_ZJDCK3HrfHM_m0it2lExgKBv3bt9A"
  VITE_ENABLE_AI_ASSISTANT = "true"
  VITE_ENABLE_VOICE_COMMANDS = "true"
  VITE_ENABLE_TRADING = "true"
  VITE_ENABLE_NOTIFICATIONS = "true"
  VITE_ENABLE_REAL_TIME_DATA = "true"
  VITE_ENABLE_ADVANCED_CHARTS = "true"
  VITE_ENABLE_MULTI_CHAIN = "true"
  VITE_ENABLE_PORTFOLIO_ANALYTICS = "true"
  VITE_ENABLE_GAMEFI = "true"
  VITE_ENABLE_DAO_FEATURES = "true"
  VITE_ENABLE_INFRASTRUCTURE_MONITORING = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
