
[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/health-check"
  to = "/.netlify/functions/health-check"
  status = 200
  force = true

[[redirects]]
  from = "/api/crypto-prices"
  to = "/.netlify/functions/crypto-prices"
  status = 200
  force = true

[[redirects]]
  from = "/api/nft-collections"
  to = "/.netlify/functions/nft-collections"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health-check"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
